"""
N8N Integration API Routes
Handles file uploads and data exchange with N8N workflows
"""
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from sqlalchemy.orm import Session
import os
from datetime import datetime

from app.utils.deps import get_db
from app.models.absence import PDFAbsence

router = APIRouter()


@router.post("/upload")
async def upload_pdf_from_n8n(
    file: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    """
    Upload PDF generated by N8N Workflow 5 (Daily absence summary).
    
    N8N sends the PDF here after generating it from Gotenberg.
    Expected filename format: absences_FS202_2025-12-21.pdf
    """
    if not file.filename.endswith('.pdf'):
        raise HTTPException(status_code=400, detail="Only PDF files are allowed")
    
    # Create upload directory if it doesn't exist
    upload_dir = "/app/storage/n8n_pdfs"
    os.makedirs(upload_dir, exist_ok=True)
    
    # Save file
    file_path = os.path.join(upload_dir, file.filename)
    with open(file_path, "wb") as f:
        content = await file.read()
        f.write(content)
    
    # Parse filename to extract class and date
    # Format: absences_FS202_2025-12-21.pdf
    try:
        parts = file.filename.replace('.pdf', '').split('_')
        if len(parts) >= 3:
            class_name = parts[1]
            date_str = parts[2]
        else:
            raise ValueError("Invalid filename format")
    except:
        # Fallback if parsing fails
        class_name = "unknown"
        date_str = datetime.now().strftime("%Y-%m-%d")
    
    # Record in database
    pdf_record = PDFAbsence(
        class_name=class_name,
        date=date_str,
        pdf_path=file_path
    )
    db.add(pdf_record)
    db.commit()
    
    return {
        "status": "success",
        "filename": file.filename,
        "path": file_path,
        "class": class_name,
        "date": date_str
    }


@router.get("/pdfs/{class_name}/{date}")
async def get_daily_pdf(
    class_name: str,
    date: str,
    db: Session = Depends(get_db)
):
    """
    Get PDF path for a specific class and date.
    
    Used by admin dashboard to download daily absence reports.
    """
    pdf = db.query(PDFAbsence).filter(
        PDFAbsence.class_name == class_name,
        PDFAbsence.date == date
    ).first()
    
    if not pdf:
        raise HTTPException(status_code=404, detail="PDF not found for this date")
    
    return {
        "class": pdf.class_name,
        "date": pdf.date,
        "pdf_path": pdf.pdf_path,
        "created_at": pdf.created_at
    }


@router.get("/pdfs/recent")
async def get_recent_pdfs(
    limit: int = 10,
    db: Session = Depends(get_db)
):
    """
    Get list of recent PDF reports.
    
    Used by admin dashboard to show available reports.
    """
    pdfs = db.query(PDFAbsence).order_by(
        PDFAbsence.created_at.desc()
    ).limit(limit).all()
    
    return [
        {
            "id": pdf.id,
            "class": pdf.class_name,
            "date": pdf.date,
            "pdf_path": pdf.pdf_path,
            "created_at": pdf.created_at
        }
        for pdf in pdfs
    ]
