"""
Absence model for N8N integration
Tracks absences for parent notification workflow
"""
from sqlalchemy import Boolean, Column, DateTime, Integer, Numeric, String
from sqlalchemy.sql import func

from app.db.base import Base


class Absence(Base):
    """Absence records for N8N notification workflow."""
    __tablename__ = "absence"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    studentid = Column(Integer, nullable=False, index=True)
    date = Column(DateTime, nullable=False)
    hours = Column(Numeric(5, 2), nullable=False)
    notified = Column(Boolean, default=False, nullable=False, index=True)
    created_at = Column(DateTime, server_default=func.now())


class PDFAbsence(Base):
    """Daily PDF absence summaries generated by N8N."""
    __tablename__ = "pdfabsences"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    class_name = Column("class", String(50), nullable=False)
    date = Column(String(20), nullable=False)
    pdf_path = Column(String(255), nullable=False)
    created_at = Column(DateTime, server_default=func.now())
