"""initial

Revision ID: 4fe2a76790ad
Revises: None
Create Date: 2025-12-15 05:17:56.743445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe2a76790ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('marked_via', sa.String(length=20), nullable=True),
    sa.Column('facial_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_photo_path', sa.String(length=255), nullable=True),
    sa.Column('marked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actual_arrival_time', sa.Time(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index('ix_attendance_session_student', 'attendance_records', ['session_id', 'student_id'], unique=False)
    op.create_index('ix_attendance_status_marked', 'attendance_records', ['status', 'marked_at'], unique=False)
    op.create_table('chatbot_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_chatbot_conversation_activity', 'chatbot_conversations', ['is_active', 'last_activity'], unique=False)
    op.create_index('ix_chatbot_conversation_user', 'chatbot_conversations', ['user_id', 'user_type'], unique=False)
    op.create_index(op.f('ix_chatbot_conversations_id'), 'chatbot_conversations', ['id'], unique=False)
    op.create_table('chatbot_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.Column('entities_extracted', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('helpful_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbot_message_conversation', 'chatbot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chatbot_messages_id'), 'chatbot_messages', ['id'], unique=False)
    op.create_table('facial_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('capture_angle', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lighting_conditions', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embeddings_image_hash', 'facial_embeddings', ['image_hash'], unique=False)
    op.create_index('ix_embeddings_student', 'facial_embeddings', ['student_id'], unique=False)
    op.create_index(op.f('ix_facial_embeddings_id'), 'facial_embeddings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_delivery_status', 'notifications', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_type_priority', 'notifications', ['notification_type', 'priority'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attendance_marked', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_date_class', 'sessions', ['session_date', 'classroom_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index('ix_sessions_trainer_status', 'sessions', ['trainer_id', 'status'], unique=False)
    op.create_index('ix_sessions_type_attendance', 'sessions', ['session_type', 'attendance_marked'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('cin_number', sa.String(length=20), nullable=True),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('parent_email', sa.String(length=100), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('parent_relationship', sa.String(length=50), nullable=True),
    sa.Column('class', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('expected_graduation', sa.Date(), nullable=True),
    sa.Column('academic_status', sa.String(length=20), nullable=True),
    sa.Column('total_absence_hours', sa.Integer(), nullable=True),
    sa.Column('total_late_minutes', sa.Integer(), nullable=True),
    sa.Column('attendance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('last_alert_date', sa.Date(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('profile_photo_path', sa.String(length=255), nullable=True),
    sa.Column('facial_data_encoded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_code')
    )
    op.create_index('ix_students_alert_level', 'students', ['alert_level', 'alert_sent'], unique=False)
    op.create_index('ix_students_class_status', 'students', ['class', 'academic_status'], unique=False)
    op.create_index('ix_students_facial_flag', 'students', ['facial_data_encoded'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('office_location', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_trainers_id'), 'trainers', ['id'], unique=False)
    op.create_index('ix_trainers_specialization', 'trainers', ['specialization'], unique=False)
    op.create_index('ix_trainers_status', 'trainers', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_trainers_status', table_name='trainers')
    op.drop_index('ix_trainers_specialization', table_name='trainers')
    op.drop_index(op.f('ix_trainers_id'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index('ix_students_facial_flag', table_name='students')
    op.drop_index('ix_students_class_status', table_name='students')
    op.drop_index('ix_students_alert_level', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_sessions_type_attendance', table_name='sessions')
    op.drop_index('ix_sessions_trainer_status', table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index('ix_sessions_date_class', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_type_priority', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notifications_delivery_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_facial_embeddings_id'), table_name='facial_embeddings')
    op.drop_index('ix_embeddings_student', table_name='facial_embeddings')
    op.drop_index('ix_embeddings_image_hash', table_name='facial_embeddings')
    op.drop_table('facial_embeddings')
    op.drop_index(op.f('ix_chatbot_messages_id'), table_name='chatbot_messages')
    op.drop_index('ix_chatbot_message_conversation', table_name='chatbot_messages')
    op.drop_table('chatbot_messages')
    op.drop_index(op.f('ix_chatbot_conversations_id'), table_name='chatbot_conversations')
    op.drop_index('ix_chatbot_conversation_user', table_name='chatbot_conversations')
    op.drop_index('ix_chatbot_conversation_activity', table_name='chatbot_conversations')
    op.drop_table('chatbot_conversations')
    op.drop_index('ix_attendance_status_marked', table_name='attendance_records')
    op.drop_index('ix_attendance_session_student', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
