"""Add session_requests table for trainer session requests

Revision ID: b59f2d127641
Revises: f1e2d3c4b5a6
Create Date: 2025-12-20 14:02:37.411516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59f2d127641'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_message_attachments_id'), 'admin_message_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_admin_message_classes_id'), 'admin_message_classes', ['id'], unique=False)
    op.create_index(op.f('ix_admin_message_trainers_id'), 'admin_message_trainers', ['id'], unique=False)
    op.alter_column('admin_messages', 'body',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_admin_messages_id'), 'admin_messages', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_alerts_id'), 'attendance_alerts', ['id'], unique=False)
    op.alter_column('attendance_records', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_attendance_sessions_id'), 'attendance_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_facial_verification_logs_id'), 'facial_verification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_detections_id'), 'fraud_detections', ['id'], unique=False)
    op.create_index(op.f('ix_message_threads_id'), 'message_threads', ['id'], unique=False)
    op.create_index(op.f('ix_message_threads_user1_id'), 'message_threads', ['user1_id'], unique=False)
    op.create_index(op.f('ix_message_threads_user2_id'), 'message_threads', ['user2_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_self_checkins_id'), 'self_checkins', ['id'], unique=False)
    op.alter_column('sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_smart_attendance_logs_id'), 'smart_attendance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_student_feedbacks_id'), 'student_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_student_feedbacks_student_id'), 'student_feedbacks', ['student_id'], unique=False)
    op.alter_column('students', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_teams_participation_id'), 'teams_participation', ['id'], unique=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_teams_participation_id'), table_name='teams_participation')
    op.alter_column('students', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_student_feedbacks_student_id'), table_name='student_feedbacks')
    op.drop_index(op.f('ix_student_feedbacks_id'), table_name='student_feedbacks')
    op.drop_index(op.f('ix_smart_attendance_logs_id'), table_name='smart_attendance_logs')
    op.alter_column('sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_self_checkins_id'), table_name='self_checkins')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_message_threads_user2_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_user1_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_id'), table_name='message_threads')
    op.drop_index(op.f('ix_fraud_detections_id'), table_name='fraud_detections')
    op.drop_index(op.f('ix_facial_verification_logs_id'), table_name='facial_verification_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_attendance_sessions_id'), table_name='attendance_sessions')
    op.alter_column('attendance_records', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_attendance_alerts_id'), table_name='attendance_alerts')
    op.drop_index(op.f('ix_admin_messages_id'), table_name='admin_messages')
    op.alter_column('admin_messages', 'body',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_message_trainers_id'), table_name='admin_message_trainers')
    op.drop_index(op.f('ix_admin_message_classes_id'), table_name='admin_message_classes')
    op.drop_index(op.f('ix_admin_message_attachments_id'), table_name='admin_message_attachments')
    # ### end Alembic commands ###
